version: '3.9'
services:
  tvapp:
    build:
      context: ./tvapp
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./test_data:/volume_data
    depends_on:
      - tvapp