version: '3.9'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - "MONGODB_INITDB_ROOT_USERNAME=${TELEVIEW_MONGODB_ROOT_USERNAME}"
      - "MONGODB_INITDB_ROOT_PASSWORD=${TELEVIEW_MONGODB_ROOT_PASSWORD}"
    volumes:
      - type: bind
        source: ./mongo
        target: /data/db
    ports:
      # open a port on the localhost computer for using the API outside a docker container
      - "${TELEVIEW_MONGODB_PORT}:${TELEVIEW_MONGODB_PORT}"

  tvapp:
    build:
      context: ./tvapp
    depends_on:
      - mongodb

  tvapi:
    build:
      context: ./tvapi
      args:
        DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
        DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
        DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
    volumes:
      - "django-static:/django/static_root"
      - "${TELEVIEW_SMURF_DATA_DIR}:/volume_data/smurf"
    depends_on:
      - mongodb
    environment:
      - "TELEVIEW_MONGODB_HOST=${TELEVIEW_MONGODB_HOST}"
      - "TELEVIEW_MONGODB_PORT=${TELEVIEW_MONGODB_PORT}"
      - "TELEVIEW_MONGODB_ROOT_USERNAME=${TELEVIEW_MONGODB_ROOT_USERNAME}"
      - "TELEVIEW_MONGODB_ROOT_PASSWORD=${TELEVIEW_MONGODB_ROOT_PASSWORD}"
      - TELEVIEW_SMURF_DATA_DIR=/volume_data/smurf
      - "TELEVIEW_VERBOSE=${TELEVIEW_VERBOSE}"
      - "TELEVIEW_DEBUG=${TELEVIEW_DEBUG}"

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - "./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro"
      - "${TELEVIEW_SMURF_DATA_DIR}:/volume_data/smurf"
      - "django-static:/django/static_root"
    depends_on:
      - tvapp
      - tvapi


volumes:
  django-static:
  smurf-data:

