version: '3.9'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./mongo
        target: /data/db
    ports:
      # open a port on the localhost computer for using the API outside a docker container
      - "27016:27017"
