version: '3.9'


services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      # These *INITDB* variables only used when the database is first initialized
      MONGODB_INITDB_ROOT_USERNAME: "${TELEVIEW_MONGODB_ROOT_USERNAME}"
      MONGODB_INITDB_ROOT_PASSWORD: "${TELEVIEW_MONGODB_ROOT_PASSWORD}"
    volumes:
      - type: bind
        source: ./mongo
        target: /data/db
    ports:
      # open a port on the localhost computer for using the API outside a docker container
      - "${TELEVIEW_MONGODB_PORT}:${TELEVIEW_MONGODB_PORT}"
    restart: always

  tvapp:
    build:
      context: ./tvapp
      args:
        # these variables are written to an .evn.production file
        # that makes these variables available in the production environment
        TELEVIEW_MONGODB_HOST: "${TELEVIEW_MONGODB_HOST}"
        TELEVIEW_MONGODB_PORT: "${TELEVIEW_MONGODB_PORT}"
        TELEVIEW_MONGODB_ROOT_USERNAME: "${TELEVIEW_MONGODB_ROOT_USERNAME}"
        TELEVIEW_MONGODB_ROOT_PASSWORD: "${TELEVIEW_MONGODB_ROOT_PASSWORD}"
        TELEVIEW_VERBOSE: "${TELEVIEW_VERBOSE}"
    image: ghcr.io/simonsobs/teleview-tvapp:LATEST
    volumes:
      # the runtime varaibles that are written to the .env.production file in the init.sh script
      - "./tvapp/.env.production:/app/.env.production:ro"
    depends_on:
      - mongodb
    restart: always

  tvapi:
    build:
      context: ./tvapi
      args:
        # these arguments all only used during the build process and are not available in the production environment
        DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
        DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
        DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
    image: ghcr.io/simonsobs/teleview-tvapi:LATEST
    volumes:
      - "${TELEVIEW_PLATFORMS_DATA_DIR}:/platforms_data:ro"
      # django-static is written at build time by the tvapi Dockerfile
      - "django-static:/django/static_root:rw"
    depends_on:
      - mongodb
    environment:
      # these variables are environment variables that are made available in the production environment
      TELEVIEW_PUBLIC_SITE_HOST: "${TELEVIEW_PUBLIC_SITE_HOST}"
      TELEVIEW_MONGODB_HOST: "${TELEVIEW_MONGODB_HOST}"
      TELEVIEW_MONGODB_PORT: "${TELEVIEW_MONGODB_PORT}"
      TELEVIEW_MONGODB_ROOT_USERNAME: "${TELEVIEW_MONGODB_ROOT_USERNAME}"
      TELEVIEW_MONGODB_ROOT_PASSWORD: "${TELEVIEW_MONGODB_ROOT_PASSWORD}"
      PLATFORMS_DATA_DIR: "/platforms_data"
      TELEVIEW_VERBOSE: "${TELEVIEW_VERBOSE}"
      TELEVIEW_DEBUG: "${TELEVIEW_DEBUG}"
    restart: always


  nginx:
    image: nginx:latest
    ports:
      - "${TELEVIEW_LOCALHOST_PORT}:8080"
    volumes:
      - "./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro"
      - "${TELEVIEW_PLATFORMS_DATA_DIR}:/platforms_data:ro"
      - "django-static:/django/static_root:ro"
    depends_on:
      - tvapp
      - tvapi
    restart: always


volumes:
  django-static:
