version: '3.8'
services:
  tvapp:
    build:
      context: ./tvapp
    environment:
      - MONGO_CONNECTION_STRING=mongodb://user:pass@mongodb:27016/?authMechanism=DEFAULT
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./mongo
        target: /data/db
    ports:
      # open a port on the localhost computer for using the API outside a docker container
      - "27016:27017"
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./test_data:/volume_data
    depends_on:
      - tvapp