# Generated by Django 4.2.1 on 2023-08-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerQueue',
            fields=[
                ('task', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerState',
            fields=[
                ('var_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('status_type', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('percent_complete', models.FloatField(default=0.0)),
                ('retry_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
