# Generated by Django 4.2.1 on 2023-06-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('status_type', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('percent_complete', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
